// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


import "./globals.css";

import {
  Plus_Jakarta_Sans,
} from "next/font/google";

const jakarta = Plus_Jakarta_Sans({

  subsets: ["latin"],

  weight: [
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
  ],

  variable: "--font-jakarta",
});

export const metadata = {

  title: "Smart RO Solution Gurugram",

  description:
    "Professional RO repair, installation and AMC service in Gurugram & Manesar.",
};

export default function RootLayout({
  children,
}) {

  return (

    <html lang="en">

      <body
        className={`${jakarta.variable} antialiased`}
      >

        {children}

      </body>

    </html>
  );
}
